<h1 id="tocheading">Table of Contents</h1>
<div id="toc"></div>

In [1]:
%%javascript
$.getScript('https://kmahelona.github.io/ipython_notebook_goodies/ipython_notebook_toc.js')

In [64]:
import pandas as pd
import numpy as np
import seaborn as sns
import pickle
import matplotlib
import matplotlib.pyplot as plt
import gc
%matplotlib inline

In [3]:
%load_ext autoreload
%autoreload 1

In [4]:
%aimport src.utils.plot
%aimport src.utils
%aimport src.feats

import src.utils as utils
import src.feats as feats

In [5]:
train = utils.read_csv('./input/application_train.csv')
buro = utils.read_csv('./input/bureau.csv')

In [6]:
cnt_buro = (
    buro[['SK_ID_CURR', 'SK_ID_BUREAU', 'CREDIT_ACTIVE']]
    .groupby(['SK_ID_CURR', 'CREDIT_ACTIVE'])
    .count().unstack().fillna(0)
    )
cnt_buro.columns = cnt_buro.columns.get_level_values(1)

In [7]:
buro['CREDIT_CURRENCY'].value_counts()

currency 1    1715020
currency 2       1224
currency 3        174
currency 4         10
Name: CREDIT_CURRENCY, dtype: int64

In [8]:
buro[buro['SK_ID_CURR'] == 215354]

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,9.132300e+04,0.000000,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,2.250000e+05,171342.000000,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,4.643235e+05,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,9.000000e+04,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2.700000e+06,NaN,NaN,0.0,Consumer credit,-21,NaN
5,215354,5714467,Active,currency 1,-273,0,27456.0,NaN,0.0,0,1.800000e+05,71017.382812,108982.617188,0.0,Credit card,-31,NaN
6,215354,5714468,Active,currency 1,-43,0,79.0,NaN,0.0,0,4.210380e+04,42103.800781,0.000000,0.0,Consumer credit,-22,NaN
225157,215354,5714458,Closed,currency 1,-1872,0,-776.0,-1203.0,NaN,0,4.945500e+05,0.000000,0.000000,0.0,Consumer credit,-696,NaN
225158,215354,5714459,Closed,currency 1,-1734,0,-638.0,-1336.0,NaN,0,1.084032e+06,0.000000,NaN,0.0,Car loan,-1336,NaN
225159,215354,5714460,Closed,currency 1,-1333,0,-1089.0,-987.0,NaN,0,1.021500e+05,NaN,NaN,0.0,Consumer credit,-984,NaN
225160,215354,5714461,Closed,currency 1,-1011,0,-830.0,-770.0,NaN,0,5.004630e+05,NaN,NaN,0.0,Consumer credit,-767,NaN

In [9]:
closed_buro = buro[buro.CREDIT_ACTIVE == 'Closed']
closed_buro

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,9.132300e+04,0.0,NaN,0.0,Consumer credit,-131,NaN
7,162297,5714469,Closed,currency 1,-1896,0,-1684.0,-1710.0,14985.000000,0,7.687845e+04,0.0,0.0,0.0,Consumer credit,-1710,NaN
8,162297,5714470,Closed,currency 1,-1146,0,-811.0,-840.0,0.000000,0,1.030077e+05,0.0,0.0,0.0,Consumer credit,-840,NaN
11,162297,5714473,Closed,currency 1,-2456,0,-629.0,-825.0,NaN,0,6.750000e+05,0.0,0.0,0.0,Consumer credit,-706,NaN
14,238881,5714482,Closed,currency 1,-318,0,-187.0,-187.0,NaN,0,0.000000e+00,0.0,0.0,0.0,Credit card,-185,NaN
15,238881,5714484,Closed,currency 1,-2911,0,-2608.0,-2604.0,NaN,0,4.855500e+04,NaN,NaN,0.0,Consumer credit,-2601,NaN
16,238881,5714485,Closed,currency 1,-2148,0,-1595.0,-987.0,NaN,0,1.350000e+05,NaN,NaN,0.0,Consumer credit,-984,NaN
19,238881,5714488,Closed,currency 1,-444,0,-77.0,-77.0,0.000000,0,1.071841e+05,0.0,0.0,0.0,Consumer credit,-71,NaN
24,222183,5714495,Closed,currency 1,-2744,0,-2560.0,-2560.0,310.500000,0,1.815750e+04,NaN,NaN,0.0,Consumer credit,-2559,NaN
25,222183,5714496,Closed,currency 1,-1103,0,-7.0,-343.0,20493.269531,0,6.750000e+05,0.0,0.0,0.0,Consumer credit,-343,NaN
27,426155,5714498,Closed,currency 1,-1331,0,-994.0,-1023.0,1350.000000,0,3.943350e+04,0.0,0.0,0.0,Consumer credit,-1023,NaN
28,426155,5714499,Closed,currency 1,-2534,0,-2352.0,-2348.0,NaN,0,3.883050e+04,0.0,0.0,0.0,Consumer credit,-2345,NaN
29,426155,5714500,Closed,currency 1,-845,0,-480.0,-480.0,0.000000,0,6.750000e+04,0.0,0.0,0.0,Consumer credit,-480,NaN
30,426155,5714501,Closed,currency 1,-529,0,-343.0,-343.0,0.000000,0,1.827914e+05,0.0,0.0,0.0,Consumer credit,-337,NaN
32,136226,5714503,Closed,currency 1,-559,0,NaN,-355.0,0.000000,0,1.102500e+05,0.0,0.0,0.0,Credit card,-351,NaN
33,400486,5714504,Closed,currency 1,-2413,0,-1864.0,-2128.0,NaN,0,1.800000e+05,0.0,0.0,0.0,Consumer credit,-708,NaN
35,400486,5714507,Closed,currency 1,-1110,0,-745.0,-727.0,NaN,0,1.147275e+05,0.0,0.0,0.0,Consumer credit,-658,NaN
36,400486,5714508,Closed,currency 1,-2133,0,-1038.0,-1127.0,NaN,0,2.250000e+05,0.0,0.0,0.0,Consumer credit,-708,NaN
38,435112,5714512,Closed,currency 1,-1412,0,-861.0,-849.0,NaN,0,8.528850e+04,0.0,0.0,0.0,Consumer credit,-753,NaN
39,435112,5714513,Closed,currency 1,-1590,0,-1344.0,-1276.0,NaN,0,1.001295e+05,0.0,0.0,0.0,Consumer credit,-783,NaN
40,435112,5714514,Closed,currency 1,-1181,0,-875.0,-872.0,NaN,0,4.441950e+04,0.0,0.0,0.0,Consumer credit,-872,NaN
41,435112,5714516,Closed,currency 1,-1475,0,-1293.0,-1322.0,NaN,0,2.169000e+04,0.0,NaN,0.0,Consumer credit,-1322,NaN
42,435112,5714517,Closed,currency 1,-1411,0,-861.0,-861.0,NaN,0,8.529300e+04,0.0,NaN,0.0,Consumer credit,-855,NaN
44,435112,5714519,Closed,currency 1,-1589,0,-1344.0,-1292.0,3980.520020,0,1.001295e+05,0.0,0.0,0.0,Consumer credit,-736,NaN
45,435112,5714520,Closed,currency 1,-829,0,-508.0,-508.0,0.000000,0,1.593861e+05,0.0,0.0,0.0,Consumer credit,-508,NaN
46,435112,5714521,Closed,currency 1,-739,0,-525.0,-525.0,0.000000,0,4.864500e+04,0.0,0.0,0.0,Consumer credit,-519,NaN
49,452585,5714524,Closed,currency 1,-2642,0,-2308.0,-2332.0,1800.000000,0,1.592100e+04,0.0,0.0,0.0,Consumer credit,-2306,NaN
52,452585,5714528,Closed,currency 1,-2898,0,-2722.0,-2344.0,NaN,0,1.134000e+04,NaN,NaN,0.0,Consumer credit,-2344,NaN
53,389599,5714529,Closed,currency 1,-672,0,10288.0,-531.0,NaN,0,1.350000e+05,0.0,0.0,0.0,Credit card,-429,NaN
54,389599,5714530,Closed,currency 1,-1304,0,1253.0,-1287.0,NaN,0,2.250000e+05,0.0,0.0,0.0,Consumer credit,-429,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716387,200106,5057431,Closed,currency 1,-2554,0,-2432.0,-2460.0,130.274994,0,1.362150e+04,0.0,0.0,0.0,Consumer credit,-2459,NaN
1716388,200106,5057442,Closed,currency 1,-898,0,-807.0,-807.0,0.000000,0,1.125000e+04,0.0,0.0,0.0,Consumer credit,-805,NaN
1716391,129669,5057475,Closed,currency 1,-918,0,-736.0,-711.0,NaN,0,9.000000e+04,NaN,NaN,0.0,Consumer credit,-708,NaN
1716392,342493,5057483,Closed,currency 1,-673,0,-583.0,-583.0,0.000000,0,1.350000e+05,0.0,0.0,0.0,Consumer credit,-556,NaN
1716393,251142,5057494,Closed,currency 1,-2023,0,-1656.0,-1838.0,NaN,0,1.215000e+05,0.0,0.0,0.0,Consumer credit,-1532,NaN
1716394,251142,5057502,Closed,currency 1,-478,0,-295.0,-295.0,0.000000,0,5.544000e+04,0.0,0.0,0.0,Consumer credit,-295,NaN
1716396,181001,5057529,Closed,currency 1,-339,0,NaN,-163.0,NaN,0,1.057500e+06,NaN,NaN,0.0,Consumer credit,-163,NaN
1716397,181001,5057533,Closed,currency 1,-911,0,-634.0,-634.0,0.000000,0,3.694500e+04,0.0,0.0,0.0,Consumer credit,-631,NaN
1716398,312021,5057541,Closed,currency 1,-1529,0,-829.0,-829.0,NaN,0,2.098980e+05,0.0,NaN,0.0,Consumer credit,-824,NaN
1716401,145715,5057569,Closed,currency 1,-2333,0,-2027.0,-1984.0,173.070007,0,3.503250e+04,0.0,0.0,0.0,Consumer credit,-1984,NaN
1716402,352358,5057580,Closed,currency 1,-1714,0,-1530.0,-1564.0,NaN,0,3.527100e+04,0.0,0.0,0.0,Consumer credit,-1532,NaN
1716405,438109,5057605,Closed,currency 1,-2390,0,-2052.0,-2082.0,11317.589844,0,1.122044e+05,0.0,0.0,0.0,Consumer credit,-2082,NaN
1716406,335468,5057618,Closed,currency 1,-2517,0,-660.0,-2364.0,0.000000,0,4.739400e+05,0.0,0.0,0.0,Car loan,-2363,NaN
1716407,146896,5057629,Closed,currency 1,-1990,0,-1244.0,-1248.0,NaN,0,9.000000e+04,NaN,NaN,0.0,Consumer credit,-1248,NaN
1716408,146896,5057632,Closed,currency 1,-434,0,-344.0,-344.0,NaN,0,2.340000e+05,0.0,NaN,0.0,Credit card,-336,NaN
1716409,146896,5057636,Closed,currency 1,-1705,0,-582.0,-582.0,0.000000,0,0.000000e+00,0.0,0.0,0.0,Credit card,-582,NaN
1716411,232118,5057652,Closed,currency 1,-821,0,-425.0,-545.0,0.000000,0,1.087657e+05,0.0,0.0,0.0,Consumer credit,-545,NaN
1716413,288038,5057665,Closed,currency 1,-463,0,-36.0,-36.0,6863.714844,0,1.108785e+05,0.0,0.0,0.0,Consumer credit,-33,NaN
1716414,445222,5057676,Closed,currency 1,-1628,0,-1320.0,-1320.0,5693.625000,0,5.783400e+04,0.0,0.0,0.0,Consumer credit,-1320,NaN
1716415,317217,5057684,Closed,currency 1,-1970,0,-1577.0,-1577.0,NaN,0,9.395550e+04,NaN,NaN,0.0,Consumer credit,-1577,NaN
1716416,433007,5057695,Closed,currency 1,-1100,0,-732.0,-731.0,NaN,0,9.877500e+04,0.0,0.0,0.0,Consumer credit,-720,NaN
1716418,433007,5057708,Closed,currency 1,-1389,0,-1299.0,-1299.0,0.000000,0,3.341584e+05,0.0,0.0,0.0,Consumer credit,-1299,NaN
1716419,352790,5057718,Closed,currency 1,-1808,0,-1596.0,-1625.0,8100.000000,0,2.824884e+04,0.0,0.0,0.0,Consumer credit,-1625,NaN
1716420,352790,5057725,Closed,currency 1,-99,0,-83.0,-98.0,NaN,0,2.700000e+04,0.0,0.0,0.0,Consumer credit,-18,NaN
1716421,375755,5057734,Closed,currency 1,-1335,0,-1152.0,-1152.0,NaN,0,1.954080e+05,0.0,NaN,0.0,Consumer credit,-1139,NaN
1716422,375755,5057742,Closed,currency 1,-2648,0,31136.0,-189.0,NaN,0,2.025000e+05,0.0,NaN,0.0,Credit card,-109,NaN
1716424,100044,5057754,Closed,currency 1,-2648,0,-2432.0,-2492.0,5476.500000,0,3.813084e+04,0.0,0.0,0.0,Consumer credit,-2493,NaN
1716425,100044,5057762,Closed,currency 1,-1809,0,-1628.0,-970.0,NaN,0,1.557000e+04,NaN,NaN,0.0,Consumer credit,-967,NaN
1716426,246829,5057770,Closed,currency 1,-1878,0,-1513.0,-1513.0,NaN,0,3.600000e+04,0.0,0.0,0.0,Consumer credit,-1508,NaN
1716427,246829,5057778,Closed,currency 1,-463,0,NaN,-387.0,NaN,0,2.250000e+04,0.0,NaN,0.0,Microloan,-387,NaN

In [10]:
buro_balance = utils.read_csv('./input/bureau_balance.csv')
buro_balance.head(30)

    SK_ID_BUREAU  MONTHS_BALANCE STATUS
0        5715448               0      C
1        5715448              -1      C
2        5715448              -2      C
3        5715448              -3      C
4        5715448              -4      C
5        5715448              -5      C
6        5715448              -6      C
7        5715448              -7      C
8        5715448              -8      C
9        5715448              -9      0
10       5715448             -10      0
11       5715448             -11      X
12       5715448             -12      X
13       5715448             -13      X
14       5715448             -14      0
15       5715448             -15      0
16       5715448             -16      0
17       5715448             -17      0
18       5715448             -18      0
19       5715448             -19      0
20       5715448             -20      X
21       5715448             -21      X
22       5715448             -22      X
23       5715448             -23      X
24       5715448             -24      X
25       5715448             -25      X
26       5715448             -26      X
27       5715449               0      C
28       5715449              -1      C
29       5715449              -2      C

In [11]:
# month = pd.cut(utils.read_csv('./input/bureau_balance.csv').MONTHS_BALANCE, bins=20)
# month
# # sns.distplot(month)

In [47]:
installment = utils.read_csv('./input/installments_payments.csv')
inst = installment
installment

,SK_ID_PREV,SK_ID_CURR,NUM_INSTALMENT_VERSION,NUM_INSTALMENT_NUMBER,DAYS_INSTALMENT,DAYS_ENTRY_PAYMENT,AMT_INSTALMENT,AMT_PAYMENT
0,1054186,161674,1.0,6,-1180.0,-1187.0,6948.359863,6948.359863
1,1330831,151639,0.0,34,-2156.0,-2156.0,1716.525024,1716.525024
2,2085231,193053,2.0,1,-63.0,-63.0,25425.000000,25425.000000
3,2452527,199697,1.0,3,-2418.0,-2426.0,24350.130859,24350.130859
4,2714724,167756,1.0,2,-1383.0,-1366.0,2165.040039,2160.584961
5,1137312,164489,1.0,12,-1384.0,-1417.0,5970.375000,5970.375000
6,2234264,184693,4.0,11,-349.0,-352.0,29432.294922,29432.294922
7,1818599,111420,2.0,4,-968.0,-994.0,17862.164062,17862.164062
8,2723183,112102,0.0,14,-197.0,-197.0,70.739998,70.739998
9,1413990,109741,1.0,4,-570.0,-609.0,14308.469727,14308.469727
10,1782554,106597,1.0,3,-933.0,-937.0,34620.523438,34620.523438
11,2558880,154793,1.0,8,-1262.0,-1269.0,15031.080078,15031.080078
12,1570206,147645,0.0,20,-761.0,-761.0,21.510000,21.510000
13,1723268,197273,1.0,14,-755.0,-800.0,6093.990234,6093.990234
14,1594684,100193,0.0,56,-1153.0,-1153.0,301.859985,301.859985
15,1456258,118323,1.0,6,-2620.0,-2620.0,4844.924805,4844.924805
16,1053286,170192,1.0,7,-500.0,-503.0,6882.839844,6882.839844
17,1410565,197687,1.0,1,-1037.0,-1048.0,12514.049805,12510.450195
18,2391610,183431,0.0,20,-1680.0,-1693.0,7875.000000,7875.000000
19,2329072,183463,1.0,11,-1699.0,-1693.0,7283.294922,7283.294922
20,1354314,196570,1.0,14,-361.0,-365.0,15219.000000,15219.000000
21,2260765,106012,3.0,23,-56.0,-59.0,13494.915039,13494.915039
22,1995642,134723,1.0,38,-1277.0,-1282.0,12949.200195,12949.200195
23,2631836,140337,0.0,116,-322.0,-322.0,560.880005,560.880005
24,2702769,102122,1.0,1,-281.0,-286.0,5178.194824,5178.194824
25,1770345,128334,1.0,5,-240.0,-255.0,10649.924805,10649.924805
26,1818333,191655,1.0,6,-345.0,-356.0,16479.269531,16479.269531
27,1991673,162903,0.0,46,-2548.0,-2560.0,5400.000000,5400.000000
28,1184783,140804,0.0,106,-155.0,-155.0,503.459991,503.459991
29,1181315,174565,1.0,7,-1894.0,-1895.0,16274.790039,16274.790039
...,...,...,...,...,...,...,...,...
13605371,1860833,415656,2.0,1,-180.0,NaN,344249.968750,NaN
13605372,1860833,415656,1.0,1,-180.0,NaN,24127.199219,NaN
13605373,1829584,450349,1.0,18,-10.0,NaN,18730.349609,NaN
13605374,1659443,405841,0.0,101,-1919.0,NaN,67.500000,NaN
13605375,2497183,419772,0.0,39,-1877.0,NaN,67.500000,NaN
13605376,1421163,453693,0.0,60,-1387.0,NaN,67.500000,NaN
13605377,2596933,419968,1.0,15,-42.0,NaN,51394.679688,NaN
13605378,2181137,409380,0.0,108,-422.0,NaN,130.500000,NaN
13605379,1062206,409297,0.0,44,-1955.0,NaN,67.500000,NaN
13605380,1421163,453693,0.0,59,-1417.0,NaN,67.500000,NaN
13605381,1263000,406628,0.0,45,-808.0,NaN,67.500000,NaN
13605382,2263477,443619,1.0,9,-61.0,NaN,5152.095215,NaN
13605383,1499195,418486,6.0,22,-412.0,NaN,48635.593750,NaN
13605384,2454112,400586,0.0,27,-1720.0,NaN,67.500000,NaN
13605385,2239217,451572,0.0,76,-131.0,NaN,46.980000,NaN
13605386,1847946,405063,0.0,40,-2056.0,NaN,0.090000,NaN
13605387,2630714,441748,1.0,4,-36.0,NaN,14707.125000,NaN
13605388,2831819,417123,0.0,8,-15.0,NaN,4399.740234,NaN
13605389,2186857,428057,0.0,69,-1532.0,NaN,67.500000,NaN
13605390,1829584,450349,1.0,16,-70.0,NaN,18730.349609,NaN
13605391,1499195,418486,6.0,32,-112.0,NaN,48635.593750,NaN
13605392,2448869,434321,1.0,16,-117.0,NaN,11504.250000,NaN
13605393,1285736,434069,0.0,73,-853.0,NaN,67.500000,NaN
13605394,1659443,405841,0.0,102,-1888.0,NaN,67.500000,NaN
13605395,1499195,418486,6.0,2,-1012.0,NaN,48635.593750,NaN
13605396,2186857,428057,0.0,66,-1624.0,NaN,67.500000,NaN
13605397,1310347,414406,0.0,47,-1539.0,NaN,67.500000,NaN
13605398,1308766,402199,0.0,43,-7.0,NaN,43737.433594,NaN
13605399,1062206,409297,0.0,43,-1986.0,NaN,67.500000,NaN
13605400,2448869,434321,1.0,19,-27.0,NaN,11504.250000,NaN

In [56]:
counts = inst[['SK_ID_CURR', 'SK_ID_PREV', 'NUM_INSTALMENT_VERSION']].groupby(['SK_ID_CURR', 'SK_ID_PREV']).count()
counts.reset_index().head()

   SK_ID_CURR  SK_ID_PREV  NUM_INSTALMENT_VERSION
0      100001     1369693                       4
1      100001     1851984                       3
2      100002     1038818                      19
3      100003     1810518                       7
4      100003     2396755                      12

In [69]:
    inst = utils.read_csv('./input/installments_payments.csv')

    inst['X_DPD'] = inst['DAYS_ENTRY_PAYMENT'] - inst['DAYS_INSTALMENT']
    inst['X_OVERDUE'] = inst['DAYS_INSTALMENT'] < inst['DAYS_ENTRY_PAYMENT']
    inst['X_OVER_PAYMENT_RATIO'] = (inst['AMT_PAYMENT'] - inst['AMT_INSTALMENT']) / inst['AMT_PAYMENT']

    # NUM_INSTALMENT_VERSION
    inst_version = inst[['SK_ID_CURR', 'SK_ID_PREV', 'NUM_INSTALMENT_VERSION']].groupby(['SK_ID_CURR', 'SK_ID_PREV']).max()
    inst_version = inst_version.reset_index().groupby('SK_ID_CURR').mean()
    inst['X_NUM_INSTALMENT_VERSION'] = inst['SK_ID_CURR'].map(inst_version['NUM_INSTALMENT_VERSION'])
    del inst['NUM_INSTALMENT_VERSION']
    del inst_version

    # 支払い回数
    nb_prevs = inst[['SK_ID_CURR', 'SK_ID_PREV']].groupby('SK_ID_CURR').count()
    inst['X_CNT_INSTALLMENT'] = inst['SK_ID_CURR'].map(nb_prevs['SK_ID_PREV'])

    # 遅延回数
    nb_overdues = inst[inst['X_OVERDUE']][['SK_ID_CURR', 'SK_ID_PREV']].groupby('SK_ID_CURR').count()
    inst['X_CNT_OVERDUE'] = inst['SK_ID_CURR'].map(nb_overdues['SK_ID_PREV'])
    inst['X_CNT_OVERDUE'] = inst['X_CNT_OVERDUE'].fillna(0)
    inst['X_OVERDUE_RATE'] = inst['X_CNT_OVERDUE'] / inst['X_CNT_INSTALLMENT']

    avg_inst = inst.groupby('SK_ID_CURR').mean()
    del inst
    gc.collect()

    for c in ['SK_ID_PREV', 'NUM_INSTALMENT_NUMBER', 'DAYS_INSTALMENT', 'DAYS_ENTRY_PAYMENT']:
        del avg_inst[c]

In [70]:
avg_inst

,AMT_INSTALMENT,AMT_PAYMENT,X_DPD,X_OVERDUE,X_OVER_PAYMENT_RATIO,X_NUM_INSTALMENT_VERSION,X_CNT_INSTALLMENT,X_CNT_OVERDUE,X_OVERDUE_RATE
SK_ID_CURR,,,,,,,,,
100001,5885.132324,5885.132324,-7.429688,0.142857,0.000000,1.500000,7,1.0,0.142857
100002,11559.247070,11559.247070,-20.421875,0.000000,0.000000,2.000000,19,0.0,0.000000
100003,64754.585938,64754.585938,-7.199219,0.000000,0.000000,1.333008,25,0.0,0.000000
100004,7096.154785,7096.154785,-7.667969,0.000000,0.000000,2.000000,3,0.0,0.000000
100005,6240.205078,6240.205078,-23.562500,0.111111,0.000000,2.000000,9,1.0,0.111111
100006,62947.085938,62947.085938,-19.375000,0.000000,0.000000,1.666992,16,0.0,0.000000
100007,12666.444336,12214.060547,-3.636719,0.227273,-332.751190,1.200195,66,15.0,0.227273
100008,27702.964844,27360.501953,26.062500,0.028571,-1.479559,1.250000,35,1.0,0.028571
100009,9568.531250,9568.531250,-8.570312,0.019608,0.000000,1.000000,51,1.0,0.019608
100010,27449.208984,27449.208984,-11.898438,0.000000,0.000000,1.000000,10,0.0,0.000000
100011,13575.715820,11328.893555,3.199219,0.138462,-1.842267,0.666504,130,18.0,0.138462
100012,9584.502930,10451.286133,-25.312500,0.104167,-10.980091,3.000000,48,5.0,0.104167
100013,10897.898438,9740.235352,-5.199219,0.064516,-46.584915,1.250000,155,10.0,0.064516
100014,11826.206055,8783.197266,-8.210938,0.421053,-2.543426,1.000000,19,8.0,0.421053
100015,7658.680664,7658.680664,-12.601562,0.100000,0.000000,1.000000,10,1.0,0.100000
100016,10739.829102,8391.646484,-1.377930,0.202703,-592.813293,1.250000,74,15.0,0.202703
100017,13508.919922,13508.919922,-10.867188,0.000000,0.000000,1.000000,30,0.0,0.000000
100018,49114.640625,49114.640625,-6.875000,0.000000,0.000000,1.333008,24,0.0,0.000000
100019,15090.468750,20636.628906,-30.500000,0.000000,0.125000,4.000000,8,0.0,0.000000
100020,7136.958496,7136.958496,-8.617188,0.000000,0.000000,1.000000,13,0.0,0.000000
100021,9059.022461,9059.022461,-12.304688,0.173913,0.000000,1.500000,23,4.0,0.173913
100022,6765.975098,6765.975098,-23.421875,0.000000,0.000000,1.000000,7,0.0,0.000000
100023,18982.580078,18982.580078,-15.695312,0.000000,0.000000,2.000000,26,0.0,0.000000
100025,36369.359375,31358.615234,-10.085938,0.326087,-1417.153320,1.500000,46,15.0,0.326087
100026,119294.593750,119294.593750,-9.375000,0.000000,0.000000,1.500000,8,0.0,0.000000
100027,24519.289062,24519.289062,-9.546875,0.000000,0.000000,1.000000,22,0.0,0.000000
100028,4979.282227,4356.731445,-3.000000,0.106195,-0.486138,1.333008,113,12.0,0.106195
100029,33917.093750,33917.093750,-19.750000,0.000000,0.000000,2.000000,4,0.0,0.000000
100030,11820.644531,11820.644531,-21.828125,0.000000,0.000000,2.000000,6,0.0,0.000000
100032,7910.762207,6780.432617,-45.843750,0.142857,-264.261719,1.000000,7,1.0,0.142857
...,...,...,...,...,...,...,...,...,...
456225,11007.808594,9379.002930,1.710938,0.365482,-inf,5.000000,197,72.0,0.365482
456226,161446.984375,161446.984375,-16.250000,0.000000,0.000000,2.000000,4,0.0,0.000000
456227,10833.899414,11438.332031,-7.824219,0.019608,-0.425314,2.199219,51,1.0,0.019608
456228,33618.800781,31976.060547,-7.285156,0.135135,-3.706910,1.333008,74,10.0,0.135135
456230,35778.949219,35778.949219,-13.906250,0.000000,0.000000,1.500000,22,0.0,0.000000
456231,42132.480469,42132.480469,-22.703125,0.000000,0.000000,1.799805,23,0.0,0.000000
456232,10326.535156,10326.535156,-14.523438,0.000000,0.000000,1.333008,25,0.0,0.000000
456233,5974.548828,5974.548828,-14.570312,0.035714,0.000000,0.500000,28,1.0,0.035714
456234,10815.625000,10461.757812,-9.289062,0.357143,-1.596404,2.500000,14,5.0,0.357143
456235,6544.707031,6544.707031,-11.609375,0.000000,0.000000,1.000000,33,0.0,0.000000
456236,12061.648438,11181.032227,-3.304688,0.091603,-69.703224,1.000000,131,12.0,0.091603
456237,20339.423828,20307.140625,-4.312500,0.029851,-1.209496,1.400391,67,2.0,0.029851
456238,24956.832031,24956.832031,-44.500000,0.000000,0.000000,2.000000,4,0.0,0.000000
456239,7191.231445,7191.231445,-4.023438,0.008333,0.000000,0.500000,120,1.0,0.008333
456240,36306.894531,33571.808594,-6.394531,0.160714,-0.912712,1.750000,56,9.0,0.160714
456241,16159.259766,15849.572266,-5.437500,0.048780,-0.050175,1.000000,41,2.0,0.048780
456242,11415.696289,11415.696289,-11.039062,0.019231,0.000000,0.750000,52,1.0,0.019231
456243,4299.790039,4299.790039,-24.953125,0.000000,0.000000,1.666992,19,0.0,0.000000
456244,42421.812500,40468.777344,-7.015625,0.082707,-282.153717,1.599609,133,11.0,0.082707
456245,5983.373047,5983.373047,-23.265625,0.000000,0.000000,1.000000,19,0.0,0.000000
456246,5218.104492,5218.104492,-5.210938,0.060606,0.000000,0.500000,33,2.0,0.060606
456247,5685.241211,5685.241211,-4.000000,0.037313,0.000000,1.000000,134,5.0,0.037313
456248,44619.085938,43887.144531,-5.128906,0.086957,-27.388643,1.000000,46,4.0,0.086957
456249,22771.410156,22771.410156,-2.500000,0.000000,0.000000,1.000000,12,0.0,0.000000
456250,13238.063477,13044.983398,-8.179688,0.060000,-0.276689,0.750000,50,3.0,0.060000
456251,7492.924316,7492.924316,-36.281250,0.000000,0.000000,2.000000,7,0.0,0.000000
456252,10069.867188,10069.867188,-2.666016,0.166667,0.000000,1.000000,6,1.0,0.166667
456253,4399.708008,4115.915039,-14.710938,0.071429,-10.335831,1.000000,14,1.0,0.071429
456254,10239.832031,10239.832031,-19.000000,0.000000,0.000000,1.000000,19,0.0,0.000000
456255,41464.714844,47646.214844,-8.070312,0.189189,-16.410275,2.333984,74,14.0,0.189189

In [55]:
nb_prevs = inst[['SK_ID_CURR', 'SK_ID_PREV']].groupby('SK_ID_CURR').count()
nb_prevs.head()

            SK_ID_PREV
SK_ID_CURR
100001               7
100002              19
100003              25
100004               3
100005               9

In [29]:
installment['DAYS_INSTALMENT'] - installment['DAYS_ENTRY_PAYMENT']

0            7.0
1            0.0
2            0.0
3            8.0
4          -17.0
5           33.0
6            3.0
7           26.0
8            0.0
9           39.0
10           4.0
11           7.0
12           0.0
13          45.0
14           0.0
15           0.0
16           3.0
17          11.0
18          13.0
19          -6.0
20           4.0
21           3.0
22           5.0
23           0.0
24           5.0
25          15.0
26          11.0
27          12.0
28           0.0
29           1.0
            ...
13605371     NaN
13605372     NaN
13605373     NaN
13605374     NaN
13605375     NaN
13605376     NaN
13605377     NaN
13605378     NaN
13605379     NaN
13605380     NaN
13605381     NaN
13605382     NaN
13605383     NaN
13605384     NaN
13605385     NaN
13605386     NaN
13605387     NaN
13605388     NaN
13605389     NaN
13605390     NaN
13605391     NaN
13605392     NaN
13605393     NaN
13605394     NaN
13605395     NaN
13605396     NaN
13605397     NaN
13605398     NaN
13605399     NaN
13605400     NaN
Length: 13605401, dtype: float16