<h1 id="tocheading">Table of Contents</h1>
<div id="toc"></div>

In [5]:
%%javascript
$.getScript('https://kmahelona.github.io/ipython_notebook_goodies/ipython_notebook_toc.js')

In [2]:
import pandas as pd
import numpy as np
import seaborn as sns
import pickle
import matplotlib
import matplotlib.pyplot as plt # for plotting
%matplotlib inline

In [3]:
%load_ext autoreload
%autoreload 1

In [4]:
%aimport src.utils.plot
%aimport src.utils
%aimport src.feats

import src.utils as utils
import src.feats as feats

In [78]:
train = utils.read_csv('./input/application_train.csv')
buro = utils.read_csv('./input/bureau.csv')

In [80]:
cnt_buro = (
    buro[['SK_ID_CURR', 'SK_ID_BUREAU', 'CREDIT_ACTIVE']]
    .groupby(['SK_ID_CURR', 'CREDIT_ACTIVE'])
    .count().unstack().fillna(0)
    )
cnt_buro.columns = cnt_buro.columns.get_level_values(1)

CREDIT_ACTIVE  Active  Bad debt  Closed  Sold
SK_ID_CURR
100001            3.0       0.0     4.0   0.0
100002            2.0       0.0     6.0   0.0
100003            1.0       0.0     3.0   0.0
100004            0.0       0.0     2.0   0.0
100005            2.0       0.0     1.0   0.0
100007            0.0       0.0     1.0   0.0
100008            1.0       0.0     2.0   0.0
100009            4.0       0.0    14.0   0.0
100010            1.0       0.0     1.0   0.0
100011            0.0       0.0     4.0   0.0
100013            0.0       0.0     4.0   0.0
100014            2.0       0.0     6.0   0.0
100015            0.0       0.0     4.0   0.0
100016            4.0       0.0     3.0   0.0
100017            0.0       0.0     6.0   0.0
100019            2.0       0.0     0.0   0.0
100020            2.0       0.0     2.0   0.0
100022            2.0       0.0     0.0   0.0
100023            4.0       0.0     9.0   0.0
100025            1.0       0.0     0.0   0.0
100026            2.0       0.0     1.0   0.0
100027            1.0       0.0     2.0   0.0
100028            5.0       0.0     7.0   0.0
100029            1.0       0.0     3.0   0.0
100030            2.0       0.0     4.0   0.0
100031            3.0       0.0     4.0   0.0
100032            1.0       0.0     3.0   0.0
100033            1.0       0.0     0.0   0.0
100035            5.0       0.0     4.0   0.0
100036            1.0       0.0     0.0   0.0
...               ...       ...     ...   ...
456220            2.0       0.0     3.0   0.0
456221            2.0       0.0     3.0   0.0
456223            1.0       0.0     4.0   0.0
456224            6.0       0.0    11.0   0.0
456225            6.0       0.0     3.0   0.0
456226            2.0       0.0     0.0   0.0
456227            2.0       0.0     2.0   0.0
456229            1.0       0.0     0.0   0.0
456230            4.0       0.0     8.0   0.0
456231            3.0       0.0     4.0   0.0
456232            2.0       0.0     0.0   0.0
456233            1.0       0.0     0.0   0.0
456234            3.0       0.0     7.0   0.0
456235            1.0       0.0     2.0   0.0
456236            4.0       0.0     9.0   0.0
456237            0.0       0.0     1.0   0.0
456238            2.0       0.0     4.0   0.0
456239            5.0       0.0     6.0   0.0
456240            1.0       0.0     1.0   0.0
456241            2.0       0.0     3.0   0.0
456242            1.0       0.0     0.0   0.0
456243            2.0       0.0     5.0   0.0
456244            4.0       0.0    19.0   0.0
456246            1.0       0.0     2.0   0.0
456247            3.0       0.0     8.0   0.0
456249            2.0       0.0    11.0   0.0
456250            2.0       0.0     1.0   0.0
456253            2.0       0.0     2.0   0.0
456254            0.0       0.0     1.0   0.0
456255            5.0       0.0     6.0   0.0

[305811 rows x 4 columns]

In [30]:
buro['CREDIT_CURRENCY'].value_counts()

currency 1    1715020
currency 2       1224
currency 3        174
currency 4         10
Name: CREDIT_CURRENCY, dtype: int64

In [69]:
buro[buro['SK_ID_CURR'] == 215354]

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,9.132300e+04,0.000000,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,2.250000e+05,171342.000000,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,4.643235e+05,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,9.000000e+04,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2.700000e+06,NaN,NaN,0.0,Consumer credit,-21,NaN
5,215354,5714467,Active,currency 1,-273,0,27456.0,NaN,0.0,0,1.800000e+05,71017.382812,108982.617188,0.0,Credit card,-31,NaN
6,215354,5714468,Active,currency 1,-43,0,79.0,NaN,0.0,0,4.210380e+04,42103.800781,0.000000,0.0,Consumer credit,-22,NaN
225157,215354,5714458,Closed,currency 1,-1872,0,-776.0,-1203.0,NaN,0,4.945500e+05,0.000000,0.000000,0.0,Consumer credit,-696,NaN
225158,215354,5714459,Closed,currency 1,-1734,0,-638.0,-1336.0,NaN,0,1.084032e+06,0.000000,NaN,0.0,Car loan,-1336,NaN
225159,215354,5714460,Closed,currency 1,-1333,0,-1089.0,-987.0,NaN,0,1.021500e+05,NaN,NaN,0.0,Consumer credit,-984,NaN
225160,215354,5714461,Closed,currency 1,-1011,0,-830.0,-770.0,NaN,0,5.004630e+05,NaN,NaN,0.0,Consumer credit,-767,NaN

In [71]:
closed_buro = buro[buro.CREDIT_ACTIVE == 'Closed']
closed_buro

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,9.132300e+04,0.0,NaN,0.0,Consumer credit,-131,NaN
7,162297,5714469,Closed,currency 1,-1896,0,-1684.0,-1710.0,14985.000000,0,7.687845e+04,0.0,0.0,0.0,Consumer credit,-1710,NaN
8,162297,5714470,Closed,currency 1,-1146,0,-811.0,-840.0,0.000000,0,1.030077e+05,0.0,0.0,0.0,Consumer credit,-840,NaN
11,162297,5714473,Closed,currency 1,-2456,0,-629.0,-825.0,NaN,0,6.750000e+05,0.0,0.0,0.0,Consumer credit,-706,NaN
14,238881,5714482,Closed,currency 1,-318,0,-187.0,-187.0,NaN,0,0.000000e+00,0.0,0.0,0.0,Credit card,-185,NaN
15,238881,5714484,Closed,currency 1,-2911,0,-2608.0,-2604.0,NaN,0,4.855500e+04,NaN,NaN,0.0,Consumer credit,-2601,NaN
16,238881,5714485,Closed,currency 1,-2148,0,-1595.0,-987.0,NaN,0,1.350000e+05,NaN,NaN,0.0,Consumer credit,-984,NaN
19,238881,5714488,Closed,currency 1,-444,0,-77.0,-77.0,0.000000,0,1.071841e+05,0.0,0.0,0.0,Consumer credit,-71,NaN
24,222183,5714495,Closed,currency 1,-2744,0,-2560.0,-2560.0,310.500000,0,1.815750e+04,NaN,NaN,0.0,Consumer credit,-2559,NaN
25,222183,5714496,Closed,currency 1,-1103,0,-7.0,-343.0,20493.269531,0,6.750000e+05,0.0,0.0,0.0,Consumer credit,-343,NaN
27,426155,5714498,Closed,currency 1,-1331,0,-994.0,-1023.0,1350.000000,0,3.943350e+04,0.0,0.0,0.0,Consumer credit,-1023,NaN
28,426155,5714499,Closed,currency 1,-2534,0,-2352.0,-2348.0,NaN,0,3.883050e+04,0.0,0.0,0.0,Consumer credit,-2345,NaN
29,426155,5714500,Closed,currency 1,-845,0,-480.0,-480.0,0.000000,0,6.750000e+04,0.0,0.0,0.0,Consumer credit,-480,NaN
30,426155,5714501,Closed,currency 1,-529,0,-343.0,-343.0,0.000000,0,1.827914e+05,0.0,0.0,0.0,Consumer credit,-337,NaN
32,136226,5714503,Closed,currency 1,-559,0,NaN,-355.0,0.000000,0,1.102500e+05,0.0,0.0,0.0,Credit card,-351,NaN
33,400486,5714504,Closed,currency 1,-2413,0,-1864.0,-2128.0,NaN,0,1.800000e+05,0.0,0.0,0.0,Consumer credit,-708,NaN
35,400486,5714507,Closed,currency 1,-1110,0,-745.0,-727.0,NaN,0,1.147275e+05,0.0,0.0,0.0,Consumer credit,-658,NaN
36,400486,5714508,Closed,currency 1,-2133,0,-1038.0,-1127.0,NaN,0,2.250000e+05,0.0,0.0,0.0,Consumer credit,-708,NaN
38,435112,5714512,Closed,currency 1,-1412,0,-861.0,-849.0,NaN,0,8.528850e+04,0.0,0.0,0.0,Consumer credit,-753,NaN
39,435112,5714513,Closed,currency 1,-1590,0,-1344.0,-1276.0,NaN,0,1.001295e+05,0.0,0.0,0.0,Consumer credit,-783,NaN
40,435112,5714514,Closed,currency 1,-1181,0,-875.0,-872.0,NaN,0,4.441950e+04,0.0,0.0,0.0,Consumer credit,-872,NaN
41,435112,5714516,Closed,currency 1,-1475,0,-1293.0,-1322.0,NaN,0,2.169000e+04,0.0,NaN,0.0,Consumer credit,-1322,NaN
42,435112,5714517,Closed,currency 1,-1411,0,-861.0,-861.0,NaN,0,8.529300e+04,0.0,NaN,0.0,Consumer credit,-855,NaN
44,435112,5714519,Closed,currency 1,-1589,0,-1344.0,-1292.0,3980.520020,0,1.001295e+05,0.0,0.0,0.0,Consumer credit,-736,NaN
45,435112,5714520,Closed,currency 1,-829,0,-508.0,-508.0,0.000000,0,1.593861e+05,0.0,0.0,0.0,Consumer credit,-508,NaN
46,435112,5714521,Closed,currency 1,-739,0,-525.0,-525.0,0.000000,0,4.864500e+04,0.0,0.0,0.0,Consumer credit,-519,NaN
49,452585,5714524,Closed,currency 1,-2642,0,-2308.0,-2332.0,1800.000000,0,1.592100e+04,0.0,0.0,0.0,Consumer credit,-2306,NaN
52,452585,5714528,Closed,currency 1,-2898,0,-2722.0,-2344.0,NaN,0,1.134000e+04,NaN,NaN,0.0,Consumer credit,-2344,NaN
53,389599,5714529,Closed,currency 1,-672,0,10288.0,-531.0,NaN,0,1.350000e+05,0.0,0.0,0.0,Credit card,-429,NaN
54,389599,5714530,Closed,currency 1,-1304,0,1253.0,-1287.0,NaN,0,2.250000e+05,0.0,0.0,0.0,Consumer credit,-429,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1716387,200106,5057431,Closed,currency 1,-2554,0,-2432.0,-2460.0,130.274994,0,1.362150e+04,0.0,0.0,0.0,Consumer credit,-2459,NaN
1716388,200106,5057442,Closed,currency 1,-898,0,-807.0,-807.0,0.000000,0,1.125000e+04,0.0,0.0,0.0,Consumer credit,-805,NaN
1716391,129669,5057475,Closed,currency 1,-918,0,-736.0,-711.0,NaN,0,9.000000e+04,NaN,NaN,0.0,Consumer credit,-708,NaN
1716392,342493,5057483,Closed,currency 1,-673,0,-583.0,-583.0,0.000000,0,1.350000e+05,0.0,0.0,0.0,Consumer credit,-556,NaN
1716393,251142,5057494,Closed,currency 1,-2023,0,-1656.0,-1838.0,NaN,0,1.215000e+05,0.0,0.0,0.0,Consumer credit,-1532,NaN
1716394,251142,5057502,Closed,currency 1,-478,0,-295.0,-295.0,0.000000,0,5.544000e+04,0.0,0.0,0.0,Consumer credit,-295,NaN
1716396,181001,5057529,Closed,currency 1,-339,0,NaN,-163.0,NaN,0,1.057500e+06,NaN,NaN,0.0,Consumer credit,-163,NaN
1716397,181001,5057533,Closed,currency 1,-911,0,-634.0,-634.0,0.000000,0,3.694500e+04,0.0,0.0,0.0,Consumer credit,-631,NaN
1716398,312021,5057541,Closed,currency 1,-1529,0,-829.0,-829.0,NaN,0,2.098980e+05,0.0,NaN,0.0,Consumer credit,-824,NaN
1716401,145715,5057569,Closed,currency 1,-2333,0,-2027.0,-1984.0,173.070007,0,3.503250e+04,0.0,0.0,0.0,Consumer credit,-1984,NaN
1716402,352358,5057580,Closed,currency 1,-1714,0,-1530.0,-1564.0,NaN,0,3.527100e+04,0.0,0.0,0.0,Consumer credit,-1532,NaN
1716405,438109,5057605,Closed,currency 1,-2390,0,-2052.0,-2082.0,11317.589844,0,1.122044e+05,0.0,0.0,0.0,Consumer credit,-2082,NaN
1716406,335468,5057618,Closed,currency 1,-2517,0,-660.0,-2364.0,0.000000,0,4.739400e+05,0.0,0.0,0.0,Car loan,-2363,NaN
1716407,146896,5057629,Closed,currency 1,-1990,0,-1244.0,-1248.0,NaN,0,9.000000e+04,NaN,NaN,0.0,Consumer credit,-1248,NaN
1716408,146896,5057632,Closed,currency 1,-434,0,-344.0,-344.0,NaN,0,2.340000e+05,0.0,NaN,0.0,Credit card,-336,NaN
1716409,146896,5057636,Closed,currency 1,-1705,0,-582.0,-582.0,0.000000,0,0.000000e+00,0.0,0.0,0.0,Credit card,-582,NaN
1716411,232118,5057652,Closed,currency 1,-821,0,-425.0,-545.0,0.000000,0,1.087657e+05,0.0,0.0,0.0,Consumer credit,-545,NaN
1716413,288038,5057665,Closed,currency 1,-463,0,-36.0,-36.0,6863.714844,0,1.108785e+05,0.0,0.0,0.0,Consumer credit,-33,NaN
1716414,445222,5057676,Closed,currency 1,-1628,0,-1320.0,-1320.0,5693.625000,0,5.783400e+04,0.0,0.0,0.0,Consumer credit,-1320,NaN
1716415,317217,5057684,Closed,currency 1,-1970,0,-1577.0,-1577.0,NaN,0,9.395550e+04,NaN,NaN,0.0,Consumer credit,-1577,NaN
1716416,433007,5057695,Closed,currency 1,-1100,0,-732.0,-731.0,NaN,0,9.877500e+04,0.0,0.0,0.0,Consumer credit,-720,NaN
1716418,433007,5057708,Closed,currency 1,-1389,0,-1299.0,-1299.0,0.000000,0,3.341584e+05,0.0,0.0,0.0,Consumer credit,-1299,NaN
1716419,352790,5057718,Closed,currency 1,-1808,0,-1596.0,-1625.0,8100.000000,0,2.824884e+04,0.0,0.0,0.0,Consumer credit,-1625,NaN
1716420,352790,5057725,Closed,currency 1,-99,0,-83.0,-98.0,NaN,0,2.700000e+04,0.0,0.0,0.0,Consumer credit,-18,NaN
1716421,375755,5057734,Closed,currency 1,-1335,0,-1152.0,-1152.0,NaN,0,1.954080e+05,0.0,NaN,0.0,Consumer credit,-1139,NaN
1716422,375755,5057742,Closed,currency 1,-2648,0,31136.0,-189.0,NaN,0,2.025000e+05,0.0,NaN,0.0,Credit card,-109,NaN
1716424,100044,5057754,Closed,currency 1,-2648,0,-2432.0,-2492.0,5476.500000,0,3.813084e+04,0.0,0.0,0.0,Consumer credit,-2493,NaN
1716425,100044,5057762,Closed,currency 1,-1809,0,-1628.0,-970.0,NaN,0,1.557000e+04,NaN,NaN,0.0,Consumer credit,-967,NaN
1716426,246829,5057770,Closed,currency 1,-1878,0,-1513.0,-1513.0,NaN,0,3.600000e+04,0.0,0.0,0.0,Consumer credit,-1508,NaN
1716427,246829,5057778,Closed,currency 1,-463,0,NaN,-387.0,NaN,0,2.250000e+04,0.0,NaN,0.0,Microloan,-387,NaN

In [89]:
buro_balance = utils.read_csv('./input/bureau_balance.csv')
buro_balance.head(30)

    SK_ID_BUREAU  MONTHS_BALANCE STATUS
0        5715448               0      C
1        5715448              -1      C
2        5715448              -2      C
3        5715448              -3      C
4        5715448              -4      C
5        5715448              -5      C
6        5715448              -6      C
7        5715448              -7      C
8        5715448              -8      C
9        5715448              -9      0
10       5715448             -10      0
11       5715448             -11      X
12       5715448             -12      X
13       5715448             -13      X
14       5715448             -14      0
15       5715448             -15      0
16       5715448             -16      0
17       5715448             -17      0
18       5715448             -18      0
19       5715448             -19      0
20       5715448             -20      X
21       5715448             -21      X
22       5715448             -22      X
23       5715448             -23      X
24       5715448             -24      X
25       5715448             -25      X
26       5715448             -26      X
27       5715449               0      C
28       5715449              -1      C
29       5715449              -2      C

In [ ]:
month = pd.cut(utils.read_csv('./input/bureau_balance.csv').MONTHS_BALANCE, bins=20)
month
# sns.distplot(month)